-- AgentDB Indexes Specification (MySQL 8.0+)
-- Demonstrates: Indexing strategies for query optimization, composite indexes, and performance tuning

USE agentdb;

-- 1. Log Timestamp Index: Accelerates log explorer date/time range filtering queries
CREATE INDEX idx_logs_timestamp ON logs(timestamp);

-- 2. Log Severity & Timestamp Composite Index: Optimizes queries filtering logs by severity (ERROR, WARNING) within specific time windows
CREATE INDEX idx_logs_severity_timestamp ON logs(severity, timestamp);

-- 3. Log Agent ID Index: Facilitates fast direct lookup of all logs generated by a specific agent (pragmatic denormalization index)
CREATE INDEX idx_logs_agent_id ON logs(agent_id);

-- 4. Log Run ID Index: Accelerates retrieving full execution logs for a specific agent run
CREATE INDEX idx_logs_run_id ON logs(run_id);

-- 5. Event Run ID Index: Speeds up rebuilding execution timeline events for individual runs
CREATE INDEX idx_events_run_id ON events(run_id);

-- 6. Event Type Index: Speeds up searching across specific event types (e.g. tool_call, api_request)
CREATE INDEX idx_events_event_type ON events(event_type);

-- 7. Run Agent ID & Status Composite Index: Optimizes status breakdown and health calculations per agent
CREATE INDEX idx_runs_agent_id_status ON runs(agent_id, status);

-- 8. Run Started At Index: Supports fast execution throughput analytics and time-series charting
CREATE INDEX idx_runs_started_at ON runs(started_at);

-- 9. Metric Run ID Index: Speeds up run performance metric extraction (latency, memory, token usage)
CREATE INDEX idx_metrics_run_id ON metrics(run_id);

-- 10. Alert Agent ID Index: Speeds up alert rule lookups for specific agents or global rules (agent_id IS NULL)
CREATE INDEX idx_alerts_agent_id ON alerts(agent_id);

-- 11. Audit Log Timestamp Index: Enables fast date-range filtering for audit and compliance reports
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp);

-- 12. Audit Log User ID Index: Fast lookup of actions performed by a specific user
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
